FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
      openssh-client \
      sshpass \
      git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir ansible-core

WORKDIR /ansible

COPY requirements.yml .
RUN ansible-galaxy collection install -r requirements.yml

CMD ["bash"]
